[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.3"

[[constraint]]
  branch = "master"
  name = "github.com/ricardo-ch/go-kafka-connect"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
